### ISSUE TITLE
API - Error 500 (Internal Server Error) on loading Users from Admin

### ISSUE THREAD

**Issue by ngangaNjiraini** [QAC-Portal/QA-Portal#64] opened 2019-12-03 10:42 UTC
In Admin section, "Manage Users" page returns a error code 500 on calling "http://localhost:4200/cohort-api/manage/users" and displays blank screen:
![Capture](https://user-images.githubusercontent.com/52919747/70043479-7471c400-15b8-11ea-994f-81f50f6ff72e.PNG)
Error code:
![errorcap](https://user-images.githubusercontent.com/52919747/70043840-198c9c80-15b9-11ea-97e3-5b4f1ecd53cc.PNG)

Seems to work fine on some PCs and not with others so more testing may be required for this.

**Comment by Lothandar** [comment] 2019-12-10 15:32
Apparently it was caused by Keycloak and is fixed in issue #77

**Closed as completed** 2019-12-11 10:12 UTC
Labels: bug, API
